"""review body and recommendations

Revision ID: 031eed5f10d2
Revises: f79cea664d20
Create Date: 2019-07-29 19:14:56.663969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '031eed5f10d2'
down_revision = 'f79cea664d20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommend',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_index(op.f('ix_recommend_user_id'), 'recommend', ['user_id'], unique=False)
    op.create_table('similarto',
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('similar_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['similar_id'], ['movie.id'], )
    )
    op.create_index(op.f('ix_similarto_movie_id'), 'similarto', ['movie_id'], unique=False)
    op.drop_index('ix_movie_imdb_rating', table_name='movie')
    op.drop_index('ix_movie_poster', table_name='movie')
    op.drop_index('ix_movie_rating', table_name='movie')
    op.add_column('review', sa.Column('body', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'body')
    op.create_index('ix_movie_rating', 'movie', ['rating'], unique=False)
    op.create_index('ix_movie_poster', 'movie', ['poster'], unique=False)
    op.create_index('ix_movie_imdb_rating', 'movie', ['imdb_rating'], unique=False)
    op.drop_index(op.f('ix_similarto_movie_id'), table_name='similarto')
    op.drop_table('similarto')
    op.drop_index(op.f('ix_recommend_user_id'), table_name='recommend')
    op.drop_table('recommend')
    # ### end Alembic commands ###
