"""new fields in user model

Revision ID: 365718bb1505
Revises: 2b7e8341ce96
Create Date: 2019-06-22 00:11:37.960191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '365718bb1505'
down_revision = '2b7e8341ce96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
