"""recommender system

Revision ID: 78d175efa33e
Revises: 031eed5f10d2
Create Date: 2019-07-30 00:00:48.750837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78d175efa33e'
down_revision = '031eed5f10d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('last_recommended', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_recommended', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_recommended')
    op.drop_column('movie', 'last_recommended')
    # ### end Alembic commands ###
